spring:
  application:
    name: servico-chamado-comunitario-api
  datasource:
    url: 'jdbc:mysql://${MYSQL_URI:localhost}:3306/${MYSQL_DATABASE:sistemaChamadodb}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:senha123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 8083